name: Build and Push Docker Image

on:
  push:
    branches:
      - main

  schedule:
    - cron: '5 3 * * 5'  # Every Friday at 03:05 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch latest yt-dlp checksum
        id: yt-dlp
        run: |
          curl -sSL https://github.com/yt-dlp/yt-dlp/releases/latest/download/SHA2-256SUMS |
          grep 'yt-dlp_linux$' > checksum.txt
          echo "checksum=$(cut -d ' ' -f1 checksum.txt)" >> "$GITHUB_OUTPUT"

      - name: Cache checksum
        id: cache-checksum
        uses: actions/cache@v3
        with:
          path: checksum.txt
          key: yt-dlp-${{ steps.yt-dlp.outputs.checksum }}

      - name: Skip build if no yt-dlp change
        if: steps.cache-checksum.outputs.cache-hit == 'true'
        run: echo "No change in yt-dlp_linux checksum, skipping build" && exit 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: servufi/video-downloader:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
